apiVersion: v2
name: text-to-video
description: End-to-End Text-to-Video API on Kubernetes using FastAPI, BentoML, and KServe
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - ai
  - ml
  - video
  - text-to-video
  - stable-diffusion
  - bentoml
  - kserve

home: https://github.com/the-dmitry-s-volkov/text-to-video
sources:
  - https://github.com/the-dmitry-s-volkov/text-to-video

maintainers:
  - name:  Dmitry Volkov 
    email: the.dmitry.s.volkov@gmail.com



annotations:
  category: AI/ML