apiVersion: v2
name: text-to-video
description: End-to-End Text-to-Video API on Kubernetes using FastAPI, BentoML, and KServe
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - ai
  - ml
  - video
  - text-to-video
  - mochi-1
  - bentoml
  - kserve

home: https://github.com/the-dsvolk/text-to-video
sources:
  - https://github.com/the-dsvolk/text-to-video

maintainers:
  - name:  Dmitry Volkov
    email: the.dsvolk@icloud.com



annotations:
  category: AI/ML
